### ISSUE TITLE
musl compatibility

### ISSUE THREAD

**Issue by Ypnose** [aperezdc/signify#5]
With [musl](http://www.musl-libc.org/) libc and a patched libbsd (built with musl), this portable version cannot be compiled. It's mostly due to <code>__BEGIN_DECLS</code> in <code>ohash.h</code> and <code>sha2.h</code>. It's not compatible with musl, the reason is [here](http://wiki.musl-libc.org/wiki/FAQ#Q:_I.27m_trying_to_compile_something_against_musl_and_I_get_error_messages_about_sys.2Fcdefs.h).  
After applying this tiny [patch](http://sprunge.us/aSdP), it can be built without issues (GCC 5.3.0). I tried with both musl and glibc. It could be kinda nice to support it upstream (in that case, upstream is here)… :+1: :smiley:

**Comment by aperezdc** [comment]
It will be nice to have this patch applied, indeed. It has not occurred to me before to build Signify with musl before, but it is a good idea to support it.

Right now I am away from a computer, so it will take a couple of days before I get to apply the patch. And thanks a lot for the contribution!

**Comment by Ypnose** [comment]
Great! I can wait until you have enough time to get into this. Thank you for the fast answer! :beers:

**Comment by aperezdc** [comment]
@Ypnose: I have just pushed the patch (commit: 706a0e8a8fb2522ce85d93609391363ac3d8f191).

Do you have around the patch needed for `libbsd`? I am considering the a Make target for building with Musl. The idea is that using a command like `make musl` will download `libbsd`, patch it and build it as a static library inside the build directory, and then use it for linking `signify`. WDYT?

**Comment by Ypnose** [comment]
Hi, I got a working patch. I'll put it here tonight. :wink:

**Comment by Ypnose** [comment]
The previous patch needed a few tweaks. <code>libbsd</code> was building fine but <code>signify</code> was still failing (because of <code>libutil.h</code> or <code>string.h</code>). The following [patch](http://sprunge.us/YCXK) allows to compile everything from scratch (<code>libbsd</code> → <code>signify</code>).

**Comment by aperezdc** [comment]
@Ypnose: Thanks a lot for the patch. I have pushed commit 50fbadc93f93a288b04a352e922cdecceba8ee19 which adds two new build options. This makes it possible to build using the following command:

```
make MUSL=1
```

or, for a static binary:

```
make MUSL=1 EXTRA_LDFLAGS=-static
```

That will download `libbsd`, patch it, and build it automatically. Depending on the command used, the resulting `signify` binary either be static, or use the Musl program interpreter, like this:

```
% readelf -l signify|grep musl
      [Requesting program interpreter: /lib/ld-musl-x86_64.so.1]
```

Could you verify that the above command works for you? 

---

(For future reference: using Arch Linux, which is my everyday system, both the `musl` and `kernel-headers-musl` packages are needed.)

**Comment by Ypnose** [comment]
I only tested the static <code>signify</code> build (disabled <code>shared</code> when I compiled <code>musl</code>) and it worked after one or two minor tweaks. I commented the lines directly on the commit.
And BTW, I see you use <code>kernel-headers-musl</code>. In my case, I used <code>4.3.x</code> or even <code>4.4.x</code> kernel headers (like yesterday when I submitted the patch) and everything is fine too.

**Comment by Ypnose** [comment]
I tested on an older box, and it was succesfully compiled (with `?=`). **Well done** :wine_glass: :jack_o_lantern:

**Comment by Ypnose** [comment]
Thank you for your valuable comments / commits :godmode:

**Comment by aperezdc** [comment]
@Ypnose: I have added a couple of commits addressing your comments. I think this issue can be considered solved. For further fixes or improvements, let's open new issues or reopen this as needed.
